# Generated by Django 3.0.5 on 2021-01-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Add', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='active',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
