# Generated by Django 3.0.5 on 2021-01-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecretUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(max_length=32, unique=True, verbose_name='Url')),
                ('expires', models.DateTimeField(verbose_name='Expires')),
            ],
        ),
    ]
